# Generated by Django 4.1.2 on 2022-10-26 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todomodel",
            name="deadline",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todomodel",
            name="priority",
            field=models.CharField(
                choices=[("danger", "high"), ("warning", "normal"), ("info", "low")],
                default="dange",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
